spring.application.name=auth-service

# database init, supports mysql too
spring.sql.init.platform=mysql
spring.datasource.url=jdbc:mysql://localhost:8000/auth_service
spring.datasource.username=alearning
spring.datasource.password=alearning
# SQL is written to be idempotent so this is safe
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath*:db/schema.sql
spring.sql.init.data-locations=classpath*:db/data.sql