spring.application.name=auth-service

# database init, supports mysql too
spring.sql.init.platform=mysql
spring.datasource.url=jdbc:mysql://localhost:8000/auth_service
spring.datasource.username=alearning
spring.datasource.password=alearning
# SQL is written to be idempotent so this is safe
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath*:db/schema.sql
spring.sql.init.data-locations=classpath*:db/data.sql

spring.web.error.include-stacktrace=on_param

app.security.jwt.token-max-interval-in-minute=30
app.security.jwt.key-id=HMo3IwaXH5
app.security.jwt.private-key-location=classpath:private-key.pem

server.port=4000