name: alearning-microservice-dev
services:
  note-service:
    ports:
      - 3333:3333
    container_name: note-service
    networks:
      - dev-net
      - backend-dev
    image: alearning-note-service
    build:
      context: .
      dockerfile: note-service/Dockerfile
      target: dev
    depends_on:
      - note-service-db
    volumes:
      - ./note-service/:/app/note-service/
      - /app/note-service/node_modules/

  note-service-db:
    container_name: note-service-db
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=alearning
      - MYSQL_PASSWORD=alearning
      - MYSQL_DATABASE=note_app
    networks:
      - backend-dev
    image: mysql:8.0

#  auth-service:
#    ports:
#      - 4000:4000
#    container_name: auth-service
#    environment:
#      - spring_datasource_url=jdbc:mysql://auth-service-db:3306/auth_service
#      - spring_datasource_username=alearning
#      - spring_datasource_password=alearning
#    networks:
#      - dev-net
#      - backend-dev
#    image: alearning-auth-service
#    build:
#      context: .
#      dockerfile: auth-service/Dockerfile
#    depends_on:
#      auth-service-db:
#        condition: service_healthy

  auth-service-db:
    container_name: auth-service-db
    ports:
      - 8000:3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=alearning
      - MYSQL_PASSWORD=alearning
      - MYSQL_DATABASE=auth_service
    networks:
      - backend-dev
    image: mysql:8.0
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "alearning", "-palearning" ]
      interval: 5s
      timeout: 5s
      retries: 10

  course-service-db:
    container_name: course-service-db
    image: postgres:16
    ports:
      - "8001:5432"
    environment:
      - POSTGRES_USER=alearning
      - POSTGRES_PASSWORD=alearning
      - POSTGRES_DB=course_service
    networks:
      - backend-dev
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U alearning -d course_service" ]
      interval: 10s
      timeout: 5s
      retries: 5

  web-client:
    ports:
      - 5173:5173
    container_name: web-client
    networks:
      - dev-net
    image: alearning-web-client
    build:
      context: .
      dockerfile: web-client/Dockerfile
      target: dev
    volumes:
      - ./web-client/:/app/web-client/
      - /app/web-client/node_modules

#  api-gateway:
#    ports:
#      - 8080:8080
#    container_name: api-gateway
#    networks:
#      - dev-net
#      - backend-dev
#    image: alearning-api-gateway
#    build:
#      context: .
#      dockerfile: api-gateway/Dockerfile
#    environment:
#      - note_service_url=http://note-service:3333

networks:
  dev-net:
  backend-dev: