name: alearning-microservice-prod
services:
  note-service-prod:
    container_name: note-service-prod
    networks:
      - note-service
      - gateway
    image: alearning-note-service-prod
    build:
      context: .
      dockerfile: note-service/Dockerfile
      target: prod
    depends_on:
      - note-service-db-prod
    env_file:
      - note-service/.env.production

  note-service-db-prod:
    container_name: note-service-db-prod
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=alearning
      - MYSQL_PASSWORD=alearning
      - MYSQL_DATABASE=note_app
    networks:
      - note-service
    image: mysql:8.0
    volumes:
      - note-service-data:/var/lib/mysql

  auth-service-prod:
    container_name: auth-service-prod
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - auth-service/.env.production
    networks:
      - auth-service
      - gateway
    image: alearning-auth-service-prod
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    depends_on:
      auth-service-db-prod:
        condition: service_healthy
    volumes:
      - ./private-key.pem:/app/private-key.pem

  auth-service-db-prod:
    container_name: auth-service-db-prod
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=alearning
      - MYSQL_PASSWORD=alearning
      - MYSQL_DATABASE=auth_service
    networks:
      - auth-service
    image: mysql:8.0
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "alearning", "-palearning" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - auth-service-data:/var/lib/mysql
  
  course-service-prod:
    container_name: course-service-prod
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - course-service/.env.production
    networks:
      - course-service
      - gateway
    image: alearning-course-service-prod
    build:
      context: .
      dockerfile: course-service/Dockerfile
    depends_on:
      course-service-db-prod:
        condition: service_healthy
    volumes:
      - ./uploads/images/:/app/uploads/images/
      - ./uploads/videos/:/app/uploads/videos/

  course-service-db-prod:
    container_name: course-service-db-prod
    image: postgres:16
    environment:
      - POSTGRES_USER=alearning
      - POSTGRES_PASSWORD=alearning
      - POSTGRES_DB=course_service
    networks:
      - course-service
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U alearning -d course_service" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - course-service-data:/var/lib/postgresql/data

  web-client-prod:
    container_name: web-client-prod
    networks:
      - frontend
    image: alearning-web-client-prod
    build:
      context: .
      dockerfile: web-client/Dockerfile
      target: prod
    volumes:
      - ./uploads/images/:/usr/share/nginx/html/uploads/images/
      - ./uploads/videos/:/usr/share/nginx/html/uploads/videos/

  api-gateway-prod:
    container_name: api-gateway-prod
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - gateway
    image: alearning-api-gateway-prod
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    depends_on:
      - auth-service-prod
      - note-service-prod
      - course-service-prod

  reverse-proxy:
    ports:
      - 80:80
    container_name: reverse-proxy
    image: reverse-proxy
    build:
      context: .
    networks:
      - frontend
      - gateway
    depends_on:
      - api-gateway-prod
      - web-client-prod

networks:
  frontend:
  gateway:
  note-service:
  auth-service:
  course-service:
volumes:
  auth-service-data:
  note-service-data:
  course-service-data: