server:
  port: 8080

note:
  service:
    url: http://localhost:3333


auth:
  service:
    url: http://localhost:4000

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:4000/.well-known/jwks.json

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service-route
              uri: http://localhost:4000
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=2

            - id: note-service-route
              uri: http://localhost:3333
              predicates:
                - Path=/api/note/**
              filters:
                - StripPrefix=2

