spring.application.name=course-service

server.port=4001

spring.sql.init.platform=postgresql
spring.datasource.url=jdbc:postgresql://localhost:8001/course_service
spring.datasource.username=alearning
spring.datasource.password=alearning

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# SQL is written to be idempotent so this is safe
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath*:db/schema.sql
spring.sql.init.data-locations=classpath*:db/data.sql

spring.web.error.include-stacktrace=on_param

## MULTIPART (MultipartProperties)
# Enable multipart uploads
spring.servlet.multipart.enabled=true
# Max file size.
spring.servlet.multipart.max-file-size=2GB
# Max Request Size
spring.servlet.multipart.max-request-size=2GB

spring.servlet.multipart.file-size-threshold=512KB

file.upload.image.upload-dir=./images
file.upload.image.allowed-types=images/jpg,images/png,images/jpeng

file.upload.video.allowed-types=video/mp4,video/webm
file.upload.video.upload-dir=./videos
file.upload.video.max-size=2GB
#file.upload.video.upload-dir=/app/uploads/videos
