spring.application.name=course-service

server.port=4001

spring.sql.init.platform=postgresql
spring.datasource.url=jdbc:postgresql://${DB_HOST:course-service-db-prod}:${DB_PORT:5432}/${DB_NAME:course_service}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# SQL is written to be idempotent so this is safe
spring.sql.init.mode=never

spring.web.error.include-stacktrace=never

## MULTIPART (MultipartProperties)
# Enable multipart uploads
spring.servlet.multipart.enabled=true
# Max file size.
spring.servlet.multipart.max-file-size=2GB
# Max Request Size
spring.servlet.multipart.max-request-size=2GB

spring.servlet.multipart.file-size-threshold=512KB

file.upload.image.upload-dir=/app/uploads/images
file.upload.image.allowed-types=images/jpg,images/png,images/jpeng

file.upload.video.allowed-types=video/mp4,video/webm
file.upload.video.upload-dir=/app/uploads/videos
file.upload.video.max-size=2GB

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWKS_URI:http://auth-service:4000/.well-known/jwks.json}
